In [3]:
#1.
#Yes, there is a difference in the data type of the list_ and array_list variables. list_ is a list of strings, while array_list is a NumPy array of strings.
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
#2.
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
#3.
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))

#Yes, there will be a difference in the data type of the elements present in list_ and array_list. the data type of each element in list_ is a string, while the data type of each element in array_list is an integer (int).

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [9]:
#4.
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [18]:
#5.
import numpy as np
# Create a 3x3 matrix containing zeros only
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#6.
import numpy as np
# Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
